/*
** PROLOGUE
**
** Provides stub function implementation for exported functions required
** to interface appliction with the Silkweed code base. 
**
** Appliction uses this as a base for its implementation, and should fill
** out the bodies as required. Included is a base implementation that 
** should be used in most cases.
*/

/*
** PREREQUISITES
*/
#include <stdlib.h>
#include <time.h>

#include "sw_app.h"
#include "sw_def.h"
#include "sw_dbg.h"
#include "sw_rnd.h"
#include "sw_gfx.h"
#include "sw_anm.h"
#include "sw_msg.h"

#include "sudoku.h"
#include "solver.h"

#include "sv.h"

/*
** DEFINITIONS
*/

static int app_initialized = 0;


/*
** EXPORTED FUNCTIONS
*/

static int wasInitialized = 0;

void swAppInit( void )
{
    SW_INFO( "AppInit()" );
    
    swInit( );
    swMsgInit( );
	swRndSeed( (int)time(NULL) );
    
    app_initialized = 1;
}

void swAppFree( void )
{
    SW_INFO( "AppFree()" );
    
    swMsgFree();
    swFree( );
}


void swAppOrientation( SW_APP_ORIENT_E orient )
{
    swGfxSetOrientation( orient );
    
    if( wasInitialized == 0 )
        return;
    
    SW_MSG_S sMsg = swMsgNull( SW_MSG_ORIENTATION );
    swMsgDispatch( sMsg );
}

void swAppDisplaySize( float dw, float dh )
{
    SW_INFOF( "AppDisplaySize() - (%f, %f)", dw, dh );
    
    swGfxSetDisplaySize( dw, dh );
}


void swAppStart( void )
{
    SW_INFO( "AppStart()" );
    
    sv_Start();
}

void swAppActive( void )
{
    SW_INFO( "AppActive()" );
    
    SW_MSG_S sMsg = swMsgNull( SW_MSG_ACTIVATE );
    swMsgDispatch( sMsg );
}

void swAppInactive( void )
{
    SW_INFO( "AppInactive()" );
    
    SW_MSG_S sMsg = swMsgNull( SW_MSG_DEACTIVATE );
    swMsgDispatch( sMsg );
}

void swAppSuspend( void )
{
    SW_INFO( "AppSuspend()" );
    
    SW_MSG_S sMsg = swMsgNull( SW_MSG_SUSPEND );
    swMsgDispatch( sMsg );
}

void swAppResume( void )
{
    SW_INFO( "AppResume()" );
    
    SW_MSG_S sMsg = swMsgNull( SW_MSG_RESUME );
    swMsgDispatch( sMsg );
}


/*
** Application processing steps.
** Called once for each update cycle generated by the Silkweed code base.
** 
** Applications should perform all general processing, excluding any
** code responsible for display, as that will be done in a separate call.
*/
void swAppProcess( void )
{
    if( app_initialized == 0 )
        return;
    
    swAnmTick( );
    
    SW_MSG_S sMsg = swMsgNull( SW_MSG_PROCESS );

    swMsgDispatch( sMsg );
    swMsgProcess();
}

void swAppDisplay( void )
{
    if( app_initialized == 0 )
        return;
        
    swGfxRenderBegin();
    
    sv_Display();
        
    swGfxRenderEnd();
}


/*
** User interaction processing functions.
** These are called whenever the user has some form of interaction
** with the device.
*/
void swAppTouch  ( float x, float y )
{
    SW_MSG_S sMsg = swMsgNull( SW_MSG_TOUCH );
    
    sMsg.fVal[0] = x;
    sMsg.fVal[1] = y;
    
    swMsgDispatch( sMsg );
}

void swAppTouchUp( float x, float y )
{
    SW_MSG_S sMsg = swMsgNull( SW_MSG_TOUCH_UP );
    
    sMsg.fVal[0] = x;
    sMsg.fVal[1] = y;
    
    swMsgDispatch( sMsg );
}

void swAppTouchMove( float x, float y )
{
    SW_MSG_S sMsg = swMsgNull( SW_MSG_TOUCH_MOVE );
    
    sMsg.fVal[0] = x;
    sMsg.fVal[1] = y;
    
    swMsgDispatch( sMsg );
}

void swAppBack( void )
{
    SW_MSG_S sMsg = swMsgNull( SW_MSG_BACK );
    
    swMsgDispatch( sMsg );
}


