#ifndef __TEX_tex_main_H__
#define __TEX_tex_main_H__
/*
** Module Prefix : tex_main_
**
** Output image definition file generated by ptp tool.
** Assumes existence of matching texture image file called tex_main.png
** The files marked [OUT] are generated ..
**
** [IN]  : tex_main.txt tex_main
** [OUT] : tex_main.h
** [OUT] : tex_main.c
*/

#if defined( __cplusplus )
    extern "C" {
#endif

/*
** PREREQUISITES
*/
#include "sw_tex.h"
#include "sw_img.h"

/*
** DEFINITIONS
*/
#define TEX_MAIN_IMG_bg_FIRST 1
#define TEX_MAIN_IMG_bg_COUNT 1

#define TEX_MAIN_IMG_board_FIRST 2
#define TEX_MAIN_IMG_board_COUNT 1

#define TEX_MAIN_IMG_btn_back_FIRST 3
#define TEX_MAIN_IMG_btn_back_COUNT 1

#define TEX_MAIN_IMG_btn_create_FIRST 4
#define TEX_MAIN_IMG_btn_create_COUNT 1

#define TEX_MAIN_IMG_btn_generate_FIRST 5
#define TEX_MAIN_IMG_btn_generate_COUNT 1

#define TEX_MAIN_IMG_btn_solve_FIRST 6
#define TEX_MAIN_IMG_btn_solve_COUNT 1

#define TEX_MAIN_IMG_btn_submit_FIRST 7
#define TEX_MAIN_IMG_btn_submit_COUNT 1

#define TEX_MAIN_IMG_peg_FIRST 8
#define TEX_MAIN_IMG_peg_COUNT 10

#define TEX_MAIN_IMG_peg_1_b_FIRST 18
#define TEX_MAIN_IMG_peg_1_b_COUNT 1

#define TEX_MAIN_IMG_peg_1_r_FIRST 19
#define TEX_MAIN_IMG_peg_1_r_COUNT 1

#define TEX_MAIN_IMG_peg_2_b_FIRST 20
#define TEX_MAIN_IMG_peg_2_b_COUNT 1

#define TEX_MAIN_IMG_peg_2_r_FIRST 21
#define TEX_MAIN_IMG_peg_2_r_COUNT 1

#define TEX_MAIN_IMG_peg_3_b_FIRST 22
#define TEX_MAIN_IMG_peg_3_b_COUNT 1

#define TEX_MAIN_IMG_peg_3_r_FIRST 23
#define TEX_MAIN_IMG_peg_3_r_COUNT 1

#define TEX_MAIN_IMG_peg_4_b_FIRST 24
#define TEX_MAIN_IMG_peg_4_b_COUNT 1

#define TEX_MAIN_IMG_peg_4_r_FIRST 25
#define TEX_MAIN_IMG_peg_4_r_COUNT 1

#define TEX_MAIN_IMG_peg_5_b_FIRST 26
#define TEX_MAIN_IMG_peg_5_b_COUNT 1

#define TEX_MAIN_IMG_peg_5_r_FIRST 27
#define TEX_MAIN_IMG_peg_5_r_COUNT 1

#define TEX_MAIN_IMG_peg_6_b_FIRST 28
#define TEX_MAIN_IMG_peg_6_b_COUNT 1

#define TEX_MAIN_IMG_peg_6_r_FIRST 29
#define TEX_MAIN_IMG_peg_6_r_COUNT 1

#define TEX_MAIN_IMG_peg_7_b_FIRST 30
#define TEX_MAIN_IMG_peg_7_b_COUNT 1

#define TEX_MAIN_IMG_peg_7_r_FIRST 31
#define TEX_MAIN_IMG_peg_7_r_COUNT 1

#define TEX_MAIN_IMG_peg_8_b_FIRST 32
#define TEX_MAIN_IMG_peg_8_b_COUNT 1

#define TEX_MAIN_IMG_peg_8_r_FIRST 33
#define TEX_MAIN_IMG_peg_8_r_COUNT 1

#define TEX_MAIN_IMG_peg_9_b_FIRST 34
#define TEX_MAIN_IMG_peg_9_b_COUNT 1

#define TEX_MAIN_IMG_peg_9_r_FIRST 35
#define TEX_MAIN_IMG_peg_9_r_COUNT 1


#define TEX_MAIN_IMG_bg_W 640
#define TEX_MAIN_IMG_bg_H 1136
#define TEX_MAIN_IMG_board_W 640
#define TEX_MAIN_IMG_board_H 640
#define TEX_MAIN_IMG_btn_back_W 80
#define TEX_MAIN_IMG_btn_back_H 75
#define TEX_MAIN_IMG_btn_create_W 300
#define TEX_MAIN_IMG_btn_create_H 124
#define TEX_MAIN_IMG_btn_generate_W 300
#define TEX_MAIN_IMG_btn_generate_H 124
#define TEX_MAIN_IMG_btn_solve_W 250
#define TEX_MAIN_IMG_btn_solve_H 85
#define TEX_MAIN_IMG_btn_submit_W 250
#define TEX_MAIN_IMG_btn_submit_H 85
#define TEX_MAIN_IMG_peg_W 64
#define TEX_MAIN_IMG_peg_H 65
#define TEX_MAIN_IMG_peg_1_b_W 64
#define TEX_MAIN_IMG_peg_1_b_H 65
#define TEX_MAIN_IMG_peg_1_r_W 64
#define TEX_MAIN_IMG_peg_1_r_H 65
#define TEX_MAIN_IMG_peg_2_b_W 64
#define TEX_MAIN_IMG_peg_2_b_H 65
#define TEX_MAIN_IMG_peg_2_r_W 64
#define TEX_MAIN_IMG_peg_2_r_H 65
#define TEX_MAIN_IMG_peg_3_b_W 64
#define TEX_MAIN_IMG_peg_3_b_H 65
#define TEX_MAIN_IMG_peg_3_r_W 64
#define TEX_MAIN_IMG_peg_3_r_H 65
#define TEX_MAIN_IMG_peg_4_b_W 64
#define TEX_MAIN_IMG_peg_4_b_H 65
#define TEX_MAIN_IMG_peg_4_r_W 64
#define TEX_MAIN_IMG_peg_4_r_H 65
#define TEX_MAIN_IMG_peg_5_b_W 64
#define TEX_MAIN_IMG_peg_5_b_H 65
#define TEX_MAIN_IMG_peg_5_r_W 64
#define TEX_MAIN_IMG_peg_5_r_H 65
#define TEX_MAIN_IMG_peg_6_b_W 64
#define TEX_MAIN_IMG_peg_6_b_H 65
#define TEX_MAIN_IMG_peg_6_r_W 64
#define TEX_MAIN_IMG_peg_6_r_H 65
#define TEX_MAIN_IMG_peg_7_b_W 64
#define TEX_MAIN_IMG_peg_7_b_H 65
#define TEX_MAIN_IMG_peg_7_r_W 64
#define TEX_MAIN_IMG_peg_7_r_H 65
#define TEX_MAIN_IMG_peg_8_b_W 64
#define TEX_MAIN_IMG_peg_8_b_H 65
#define TEX_MAIN_IMG_peg_8_r_W 64
#define TEX_MAIN_IMG_peg_8_r_H 65
#define TEX_MAIN_IMG_peg_9_b_W 64
#define TEX_MAIN_IMG_peg_9_b_H 65
#define TEX_MAIN_IMG_peg_9_r_W 64
#define TEX_MAIN_IMG_peg_9_r_H 65

/*
** EXPORTED VARIABLES
*/
extern SWtexture tex_main_texture;
extern SWimage   tex_main_images[ 36 ];

/*
** EXPORTED FUNCTIONS
*/
void tex_main_LoadImages  ( void );
void tex_main_UnloadImages( void );

#if defined( __cplusplus )
    }
#endif

#endif /* __TEX_tex_main_H__ */

